# Generated by Django 6.0.3 on 2026-03-18 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(default="N/A"),
        ),
        migrations.AddField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="product",
            name="name",
            field=models.CharField(default="N/A", max_length=150),
        ),
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
