# Generated by Django 6.0.3 on 2026-03-25 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_product_description_product_is_active_product_name_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ProductCategory",
            new_name="Category",
        ),
    ]
