# Generated by Django 6.0.3 on 2026-04-01 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_category_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(),
        ),
    ]
